name: Debug Repo Layout (temporary)

on:
  workflow_dispatch:   # allows manual run from Actions page
  push:
    branches: [ main ] # optional: will also run on pushes

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show root working directory and list files
        run: |
          echo ">>> pwd (root):"
          pwd
          echo
          echo ">>> ls -la (root):"
          ls -la
          echo
          echo ">>> recursive listing (root):"
          ls -R

      - name: Show full path of all package.json files
        run: |
          echo ">>> find package.json files (up to 5 levels):"
          find . -maxdepth 5 -name 'package.json' -print -exec ls -l {} \; || true

      - name: Show sizes of top folders
        run: |
          echo ">>> top-level folders and counts:"
          for d in *; do [ -d "$d" ] && echo "DIR: $d" && ls -la "$d" | head -n 20; done

